import { EngineConfigurationOption, NameText, UnitText } from 'sonolus-core'

export const optionsDefinition = {
    autoplay: {
        name: NameText.AutoPlay,
        scope: 'Sekai',
        standard: true,
        type: 'toggle',
        def: 0,
    },
    speed: {
        name: NameText.LevelSpeed,
        standard: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    hidden: {
        name: NameText.Hidden,
        standard: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    noteSpeed: {
        name: NameText.NoteSpeed,
        scope: 'Sekai',
        type: 'slider',
        def: 6,
        min: 1,
        max: 12,
        step: 0.1,
    },
    mirror: {
        name: NameText.MirrorLevel,
        type: 'toggle',
        def: 0,
    },
    sfxEnabled: {
        name: NameText.SFX,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    autoSFX: {
        name: NameText.AutoSFX,
        scope: 'Sekai',
        type: 'toggle',
        def: 0,
    },
    noteEffectEnabled: {
        name: NameText.NoteEffect,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    noteEffectSize: {
        name: NameText.NoteEffectSize,
        scope: 'Sekai',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    markerAnimation: {
        name: NameText.MarkerAnimation,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    simLineEnabled: {
        name: NameText.SimultaneousLineVisibility,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    connectorAnimation: {
        name: NameText.ConnectorAnimation,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    laneEffectEnabled: {
        name: NameText.LaneEffect,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    slotEffectEnabled: {
        name: NameText.SlotEffect,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    slotEffectSize: {
        name: NameText.SlotEffectSize,
        scope: 'Sekai',
        type: 'slider',
        def: 1,
        min: 0,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    stageCover: {
        name: NameText.VerticalStageCover,
        scope: 'Sekai',
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    lockStageAspectRatio: {
        name: NameText.LockStageAspectRatio,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
} as const satisfies Record<string, EngineConfigurationOption>
