import { defineOptions } from 'sonolus.js'

export const options = defineOptions({
    isAutoplay: {
        name: '#AUTO',
        scope: 'Sekai',
        standard: true,
        type: 'toggle',
        def: 0,
    },
    speed: {
        name: '#SPEED',
        standard: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        display: 'percentage',
    },
    noteSpeed: {
        name: '#NOTE_SPEED',
        scope: 'Sekai',
        type: 'slider',
        def: 6,
        min: 1,
        max: 12,
        step: 0.1,
        display: 'number',
    },
    connectorAlpha: {
        name: '#CONNECTOR_ALPHA',
        scope: 'Sekai',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 1,
        step: 0.05,
        display: 'percentage',
    },
    stageCover: {
        name: '#STAGE_COVER_VERTICAL',
        scope: 'Sekai',
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        display: 'percentage',
    },
    isMirrorEnabled: {
        name: '#MIRROR',
        type: 'toggle',
        def: 0,
    },
    isSimLineEnabled: {
        name: '#SIMLINE',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    isSFXEnabled: {
        name: '#EFFECT',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    isNoteEffectEnabled: {
        name: '#NOTE_EFFECT',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    isLaneEffectEnabled: {
        name: '#LANE_EFFECT',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    isSlotEffectEnabled: {
        name: '#SLOT_EFFECT',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    isStageAspectRatioLocked: {
        name: '#STAGE_ASPECTRATIO_LOCK',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
})
