import { NameText, UnitText } from 'sonolus-core'
import { defineOptions } from 'sonolus.js'

export const options = defineOptions({
    isAutoplay: {
        name: NameText.AutoPlay,
        scope: 'Sekai',
        standard: true,
        type: 'toggle',
        def: 0,
    },
    hidden: {
        name: NameText.Hidden,
        standard: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    speed: {
        name: NameText.LevelSpeed,
        standard: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    noteSpeed: {
        name: NameText.NoteSpeed,
        scope: 'Sekai',
        type: 'slider',
        def: 6,
        min: 1,
        max: 12,
        step: 0.1,
    },
    noteEffectSize: {
        name: NameText.NoteEffectSize,
        scope: 'Sekai',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    slotEffectSize: {
        name: NameText.SlotEffectSize,
        scope: 'Sekai',
        type: 'slider',
        def: 1,
        min: 0,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    connectorAlpha: {
        name: NameText.ConnectorTransparency,
        scope: 'Sekai',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 1,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    stageCover: {
        name: NameText.VerticalStageCover,
        scope: 'Sekai',
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    isMirrorEnabled: {
        name: NameText.MirrorLevel,
        type: 'toggle',
        def: 0,
    },
    isSimLineEnabled: {
        name: NameText.SimultaneousLineVisibility,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    isSFXEnabled: {
        name: NameText.SFX,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    isAutoSFX: {
        name: NameText.AutoSFX,
        scope: 'Sekai',
        type: 'toggle',
        def: 0,
    },
    isNoteEffectEnabled: {
        name: NameText.NoteEffect,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    isLaneEffectEnabled: {
        name: NameText.LaneEffect,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    isSlotEffectEnabled: {
        name: NameText.SlotEffect,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    isStageAspectRatioLocked: {
        name: NameText.LockStageAspectRatio,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
})
